### ISSUE TITLE
Логирование ошибок

### ISSUE THREAD

**Issue by vporoshok** [sorrat/url_grabber#1]
можно ли добавить логирование ошибок в StdErr

**Comment by sorrat** [comment]
[log](https://golang.org/src/log/log.go) по умолчанию отправляет сообщения в `stderr`. 
Конечно, при необходимости можно разделить обычные сообщения и ошибки по разным потокам.

**Comment by vporoshok** [comment]
да, проглядел, действительно используется log и для ошибок и для вывода
